### ISSUE TITLE
Sample wanted for Konad library

### ISSUE THREAD

**Issue by lucapiccinelli** [LouisCAD/kotlin-libraries-playground#95]
## About the library

- *Description*:   Simple Kotlin monads for everyday error handling. Easy to use for OOP developers.
- *GitHub*:  https://github.com/lucapiccinelli/konad
- *Official website*:  https://github.com/lucapiccinelli/konad

## What the sample could do

 - Provide an example of how to compose independently computed `Result<T>`.
 - Provide an example of how to compose independently computed nullables.

## Wants to contribute the sample?

- Say so in a comment here
- Follow instructions in [CONTRIBUTING.md](https://github.com/LouisCAD/kotlin-libraries-playground/blob/main/CONTRIBUTING.md)
- Submit your pull request!

**Comment by lucapiccinelli** [comment]
Konad is a new library for Kotlin. It is not yet known to the mass. Please tell me if you are interested in having an example in your playground. If you are not interested, feel free to close the issue.

I wrote an article [here](https://hackernoon.com/kotlin-nullables-how-to-compose-them-right-xm1634cu) about a use case.

Thank you

**Comment by jmfayard** [comment]
Hello Luca, happy to have a sample for Konad

**Comment by lucapiccinelli** [comment]
Dear Jean, I got this error running the _main.kt

`Test: User(id=1, name=Adam)
Test: {"id" : 1, "name" : "Adam"}
Exception in thread "main" java.lang.UnsatisfiedLinkError: C:\Users\luca.piccinelli\AppData\Local\Kodein-DB\0.4.0-beta\libkodein-leveldb-jni.dll: Can't find dependent libraries
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2430)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2487)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2684)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2617)
        at java.base/java.lang.Runtime.load0(Runtime.java:767)
        at java.base/java.lang.System.load(System.java:1831)
        at org.kodein.db.leveldb.jvm.AbstractLevelDBJvmLoader.load(AbstractLevelDBJvmLoader.kt:77)
        at org.kodein.db.leveldb.jvm.LevelDBJvm.<clinit>(LevelDBJvm.kt:28)
        at org.kodein.db.impl.data.DataDBJvm.getLdbFactory(DataDBJvm.kt:10)
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:18)
        at org.kodein.db.impl.data.AbstractDataDBFactory.open(AbstractDataDBFactory.kt:11)
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:21)
        at org.kodein.db.impl.model.AbstractModelDBFactory.open(AbstractModelDBFactory.kt:9)
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:25)
        at org.kodein.db.impl.AbstractDBFactory.open(AbstractDBFactory.kt:10)
        at org.kodein.db.impl.DefaultKt.open(default.kt:7)
        at playground.kodein.db.KodeinDBKt.main(KodeinDB.kt:24)
        at playground._mainKt.main(_main.kt:20)
        at playground._mainKt.main(_main.kt)
`

Complete log here on pastebin https://pastebin.com/MkrygSsN. 
I'm using AdoptOpenJDK\jdk-11.0.4.11-hotspot as Jdk implementation
